AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - define
    - create_program

Naming/FileName:
  Enabled: false
